### ISSUE TITLE
IKVM cannot open jars that include additional zip header information.

### ISSUE THREAD

**Issue by e3ndr** [jessielesbian/ikvm#1]
Basically some programs will include some exe information in the jar header, that the jvm ignores but windows can use to run a script (ex: `bin/java/java -jar some.exe`). The [old minecraft launcher](https://web.archive.org/web/20170105015443/https://s3.amazonaws.com/Minecraft.Download/launcher/Minecraft.exe) does this.

Noticed this in the original and its present in this fork.

**Comment by MuhammadMinh** [comment]
This is a problem with SharpZipLib, the zip library IKVM used to read the jar file. Talk to the SharpZipLib devs, not me.
