### ISSUE TITLE
Migrate to .Net (Core)

### ISSUE THREAD

**Issue by SupinePandora43** [jessielesbian/ikvm#16]

**Comment by orellabac** [comment]
Is there any efforts on migrating to .Net Core? 

Well .NET 6 or .NET 7?

**Comment by trungnt2910** [comment]
I might look into this after #18 is resolved, in a fork of my own.

The first thing to do is to get a proper `.gitignore` file for this project, and then split the C# part and the native parts to see which can be upgraded to `.NET 6`.

And it's either .NET 6 or .NET 8, projects should stick to LTS releases unless there are new features projects can't live without.

**Comment by wasabii** [comment]
@trungnt2910  https://github.com/ikvm-revived/ikvm

**Comment by trungnt2910** [comment]
> @trungnt2910  https://github.com/ikvm-revived/ikvm
> 
> 

Nice, first time I saw a "proper" IKVM fork that's still alive.

**Comment by wasabii** [comment]
> 

https://www.nuget.org/packages/IKVM/8.2.0-prerelease0392
