### ISSUE TITLE
Exception in thread "main" java.awt.AWTError: Toolkit not found: ikvm.awt.NetToolkit

### ISSUE THREAD

**Issue by jayjupdhig** [jessielesbian/ikvm#2]
same Problem as on original IVKM Version:

```
C:\Users\*****\Desktop\Eclipse Workspaces\Java\ftp_test\release>app.exe
Exception in thread "main" java.awt.AWTError: Toolkit not found: ikvm.awt.NetToolkit, IKVM.AWT.WinForms, Version=8.5.0.3
, Culture=neutral, PublicKeyToken=null
        at java.awt.Toolkit$2.run(Unknown Source)
        at java.awt.Toolkit$2.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Unknown Source)
        at java.security.AccessController.doPrivileged(Unknown Source)
        at java.awt.Toolkit.getDefaultToolkit(Unknown Source)
        at java.awt.Toolkit.getEventQueue(Unknown Source)
        at java.awt.EventQueue.invokeLater(Unknown Source)
        at ftp_test.Form.showForm(Form.java:60)
        at ftp_test.Main.<init>(Main.java:11)
        at ftp_test.Main.main(Main.java:16)
Exception in thread "Thread-0" java.lang.ExceptionInInitializerError: java.lang.ClassCastException: Das Objekt des Typs
"java.util.PropertyResourceBundle" kann nicht in Typ "sun.util.resources.OpenListResourceBundle" umgewandelt werden.
        at com.enterprisedt.net.ftp.FileTransferClient.<init>(FileTransferClient.java)
        at ftp_test.FTPRunnable.run(FTPRunnable.java:48)
        at java.lang.Thread.run(Unknown Source)


```

why?

thx for Feedback.

**Comment by jayjupdhig** [comment]
"The class ikvm.awt.NetToolkit is in the assembly IKVM.AWT.WinForms."

That seems to be wrong - doesn't help!

-> https://stackoverflow.com/questions/12599507/c-sharp-ikvm-toolkit-not-found-exception

**Comment by jayjupdhig** [comment]
maybe it is fixed in the master branch??

**Comment by jayjupdhig** [comment]
No anwser is also an awswer. ;-)

Seriously: That's just ridiculous, not less and not more!! So WTF?

(Btw. i don't like lesbians!!)

**Comment by jayjupdhig** [comment]
Problem solved by not-using your crappy product!!

So long...

**Comment by ghost** [comment]
You are 因缺思厅

**Comment by jayjupdhig** [comment]
Please write in english - don't understand. Neither your secret characters, nor your secret language!! ;-)

**Comment by jayjupdhig** [comment]
No understand!! ;-)

**Comment by jayjupdhig** [comment]
Google Translator says me:

"因缺思厅" means "Room for a lack of thinking" (???)

Better to be "a room for a lack of thinking" (whatever that is!?) than to be homo - that's, at least, just my humble opinion.

So long...

**Comment by wherewhere** [comment]
因缺思厅 is sound like Interesting in Chinese. LoL
You need copy `IKVM.AWT.WinForms.dll` to your exe dir.

**Comment by kosuodhmwa** [comment]
Thank you very much for your feedback. **And sorry for my bad words, i was a lil bit stressed 2 years ago - due to some things, for example that COVID s**t...**

**-> The IKVM technology seems to be "obsolete" now... but if there is an IKVM version that works with .NET Framework > 2.0, or, much more better, with the new "Core" versions of it - that would be very interesting i.m.o.!! :-)**

**Comment by kosuodhmwa** [comment]
(This is my personal account, **@jayjupdhig** is my business / workplace account)

**Comment by kosuodhmwa** [comment]
-> https://github.com/jessielesbian/ikvm/issues/19

**Comment by wherewhere** [comment]
Maybe you need this.
https://github.com/ams-ts-ikvm/ikvm/tree/net_core_compat

**Comment by kosuodhmwa** [comment]
Thank you very very much for your fast feedback!! :-)

**Comment by wherewhere** [comment]
LOL😙

**Comment by kosuodhmwa** [comment]
No really - at least so it seems:

![image](https://user-images.githubusercontent.com/24782840/167854717-34005713-d46e-48ec-96c4-b256cad78623.png)

**Comment by kosuodhmwa** [comment]
**Or can i use that 2.0 assembly in Core 3.1 without any problems...?**

**Comment by wherewhere** [comment]
I found that on this article. You can use translater to read it.
https://blog.csdn.net/sD7O95O/article/details/121528114

**Comment by kosuodhmwa** [comment]
Thank you very much, looks very interesting!

**Comment by GeorgeS2019** [comment]
Continue the AWT discussion here in 2022
https://github.com/ikvm-revived/ikvm/issues/144
