### ISSUE TITLE
java.util.MissingResourceException: 'Can't find bundle for base name sun.text.resources.FormatData, locale en_150'

### ISSUE THREAD

**Issue by emnh** [jessielesbian/ikvm#5]
I've converted a project using IKVM. It worked using an older version from ikvm.net, but now using your version I'm getting:

java.util.MissingResourceException: 'Can't find bundle for base name sun.text.resources.FormatData, locale en_150'

**Comment by emnh** [comment]
I recompiled my project with your binaries. I didn't recompile your project.

I ended up using https://chocolatey.org/packages/ikvm. That one worked for me.

**Comment by MuhammadMinh** [comment]
It's likely that this issue has been corrected as part of the OpenJDK version upgrade.
